services:
  # Production database (PostgreSQL)
  shiptrack-db-prod:
    image: postgres:15-alpine
    container_name: shiptrack-db-prod
    environment:
      POSTGRES_DB: shiptrack_prod
      POSTGRES_USER: shiptrack
      POSTGRES_PASSWORD: shiptrack_password
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - prod

  # Development database (PostgreSQL)
  shiptrack-db-dev:
    image: postgres:15-alpine
    container_name: shiptrack-db-dev
    environment:
      POSTGRES_DB: shiptrack_dev
      POSTGRES_USER: shiptrack
      POSTGRES_PASSWORD: shiptrack_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    profiles:
      - dev

  # Production application
  shiptrack-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipTrack-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://shiptrack:shiptrack_password@shiptrack-db-prod:5432/shiptrack_prod
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NEXTAUTH_SECRET=your-nextauth-secret
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - shiptrack-db-prod
    restart: unless-stopped
    profiles:
      - prod

  # Development application
  shiptrack-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shiptrack-app-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://shiptrack:shiptrack_password@shiptrack-db-dev:5432/shiptrack_dev
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - NEXTAUTH_SECRET=your-nextauth-secret
      - NEXTAUTH_URL=http://localhost:3001
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - shiptrack-db-dev
    restart: unless-stopped
    profiles:
      - dev

volumes:
  postgres_prod_data:
  postgres_dev_data:
